### PR TITLE
INTPYTHON-407 Add evergreen configuration for django-mongodb

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by timgraham** [comment]
- Does this take the place of `.ghub/workflows/tests.yml`? (I don't see that status reported anymore.)
- Are the results of evergreen builds not publicly available? (e.g. for non-employee contributors)
- Have we lost the path filtering functionality to avoid unneeded builds? https://github.com/mongodb-labs/django-mongodb/blob/087000ef579cab1e205725b0f5b38bc3ae09480b/.github/workflows/test-python.yml#L5-L8
- The build uses Python 3.11 but it would be better to use 3.10 since that's the minimum version supported by Django 5.0.
- It appears I don't have access to the Jira ticket, so perhaps I'm missing some explanation about this.

**Comment by timgraham** [comment]
Thanks for the explanations. It looks good to me, but I'll leave the approval to Jib.

May I ask that when using GitHub's "squash and merge" button, please clear the "extended description" box that automatically includes a bulleted list of every commit that was squashed (e.g. fba889204de5338b41cd7e00ee04181051a1b0fb)? We don't need that info cluttering our git log. Thanks.

**Comment by blink1073** [comment]
Yep, I use refined github's `pr-first-commit-title` to do that automatically.

**Review by Jibola — APPROVED** [review]
LGTM

**Pull request merged**
