### PR TITLE
make QuerySet.exclude() range lookup exclude data with a null boundary

### PR DESCRIPTION
**Pull request by WaVEV**

### CODE REVIEW

**Comment by timgraham** [comment]
I wonder about the behavior when an endpoint is null. Example:
```python
queryset = SimulationRun.objects.filter(
    midpoint__range=[F("start__time"), None]
)
self.assertSequenceEqual(queryset, [])
```
On SQLite and PostgreSQL, the SQL `WHERE "midpoint" BETWEEN "time" AND NULL` returns no results.

With this patch, MongoDB returns `[s1, s2]`.

But I'm not sure if this is a valid use case since Django doesn't document or test it. And actually, MongoDB's results seem reasonable if you interpret `range=[F("start__time"), None]` as meaning "give me values from the start time to the end of all time".

**Comment by WaVEV** [comment]
> I wonder about the behavior when an endpoint is null. Example:
> 
> ```python
> queryset = SimulationRun.objects.filter(
>     midpoint__range=[F("start__time"), None]
> )
> self.assertSequenceEqual(queryset, [])
> ```
> 
> On SQLite and PostgreSQL, the SQL `WHERE "midpoint" BETWEEN "time" AND NULL` returns no results.
> 
> With this patch, MongoDB returns `[s1, s2]`.
> 
> But I'm not sure if this is a valid use case since Django doesn't document or test it. And actually, MongoDB's results seem reasonable if you interpret `range=[F("start__time"), None]` as meaning "give me values from the start time to the end of all time".

Well, I misunderstood it. I thought that None allows us to get values from the start time to the end of all time.

**Comment by timgraham** [comment]
It might be fine. I found that at least for [Microsoft's SQL](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/between-transact-sql): "If any input to the BETWEEN or NOT BETWEEN predicate is NULL, the result is UNKNOWN."

**Comment by WaVEV** [comment]
> It might be fine. I found that at least for [Microsoft's SQL](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/between-transact-sql): "If any input to the BETWEEN or NOT BETWEEN predicate is NULL, the result is UNKNOWN."

"While it is a valid definition, the issue is in how we handle `Null` or `None` values. I don't believe this change fixes the test.

**Comment by timgraham** [comment]
What I mean is that I'm not sure we have to match the behavior on SQLite/PostgreSQL, since the expected result isn't well-defined by the SQL standard.

**Review by timgraham — APPROVED** [review]

**Pull request merged**
